YOLOV3:
  CFG: "./detector/YOLOv3/cfg/yolov3-evade.cfg"
  WEIGHT: "./detector/YOLOv3/weight/yolov3-evade.weights"
  CLASS_NAMES: "./detector/YOLOv3/cfg/evade.names"

  SCORE_THRESH: 0.3
  NMS_THRESH: 0.45
