YOLOV3:
  CFG: "./detector/YOLOv3/cfg/layer_prune_12_shortcut_yolov3-evade.cfg"
  WEIGHT: "./detector/YOLOv3/weight/layer_prune_finetune_last.weights"
  CLASS_NAMES: "./detector/YOLOv3/cfg/evade.names"

  SCORE_THRESH: 0.3
  NMS_THRESH: 0.45
