YOLOV5:
  CFG: "./detector/YOLOv5/models/yolov5m-evade.yaml"
  WEIGHT: "./detector/YOLOv5/weight/m_evade_last_320_1000_20201023.pt"
  CLASS_NAMES: "./detector/YOLOv5/cfg/evade.names"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4

  agnostic_nms: False
  augment: False
  conf_thres: 0.3
  half: False
  img_size: 320
  iou_thres: 0.45
  opt_classes: None
